// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmltjekfuciwtnnkvjfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbHRqZWtmdWNpd3Rubmt2amZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDUwNjMsImV4cCI6MjA3MTE4MTA2M30.IM2a58300rSKFhMFGF9-qKDXUBQQm7dJ9S-uk7o_g0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});